### ISSUE TITLE
OPENAI_MODEL_OVERRIDE="gpt-4" leads to 404 error

### ISSUE THREAD

**Issue by untcha** [ibigio/shell-ai#15]
Exporting OPENAI_MODEL_OVERRIDE="gpt-4" leads to the following error:

``` bash
  Error: Failed to connect to OpenAI.

  API request failed: 404 Not Found
```

**Comment by eugenio-mercuriali** [comment]
Have you tried wrapping your OpenAI key in square brackets when running `export OPENAI_API_KEY= ...` ?

**Comment by untcha** [comment]
When I wrap the API key into square brackets, I get an 401

```
  Error: Failed to connect to OpenAI.

  API request failed: 401 Unauthorized
```

Without wrapping, it works fine, except that I cannot override the model.

**Comment by ibigio** [comment]
No brackets – you might not have access to GPT4? I think you get access after paying your first OpenAI bill (even if it's like < $1) – do you have access to GPT4 on the [OpenAI playground](https://platform.openai.com/playground)?

**Comment by untcha** [comment]
Thanks a lot for that interesting information. Just checked the OpenAI playground and there I only have access to GPT3 models.
I also checked "Lori" (an App I use on iOS and macOS) which gives me also an error when using GPT4 and a hint to this FAQ article from OpenAI:
https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

It is like you said, but the amount is $1 or greater.

Thanks a lot for your help!
