### ISSUE TITLE
Unable to connect to OpenAI

### ISSUE THREAD

**Issue by eugenio-mercuriali** [ibigio/shell-ai#16]
**Context**

It does not seem possible to connect to OpenAI, even with a newly generated API key.
Installed via brew.

![image](https://github.com/ibigio/shell-ai/assets/102968488/ce737ba9-4714-43f6-bca2-1a21f8300d57)

**Comment by ibigio** [comment]
- Did you set up billing?
- Are you using 3.5 or 4? (Apparently access to 4 requires having paid your first bill)
